services:
  core-simulator:
    build: ../../core-simulator/
    container_name: core-simulator
    image: openexposure/coresim:local
    volumes:
      - ./config/coreSim.yaml:/etc/config.yaml
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9090:9090"   # Prometheus metrics
    healthcheck:
      test: ["CMD", "curl", "localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      coresim_net:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      coresim_net:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yml

    ports:
      - "3000:3000"   # Grafana UI
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    networks:
      coresim_net:



networks:
  coresim_net:
    name: coresim-bridge
    driver: bridge
